name: Semantic PR title

on:
  pull_request:

concurrency:
  group: env-${{ github.ref }}

jobs:
  semantic-pr-title:
    name: Semantic PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
