name: Semantic PR title

on:
  pull_request:
    branches:
      - main

concurrency:
  group: env-${{ github.ref }}

jobs:
  semantic-pr-title:
    name: Semantic PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
